### ISSUE TITLE
git not found in docker image

### ISSUE THREAD

**Issue by janonym1** [turt2live/matrix-dimension#445] opened 2021-11-25 14:43 UTC
After updating, I am getting the following error when I try to start matrix-dimension service:
```
Starting matrix-dimension
 version Error: Cannot find module '../package.json'
[...]
 /bin/sh: git: not found
 version Error: Command failed: git rev-parse --short HEAD
: /bin/sh: git: not found
[...]
```

I am using the matrix-docker-ansible-deploy playbook and according to https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/1314 the Dockerfile does not install git anymore? 
Quoting @spantaleev:
"Dimension tries to figure out its own version by running git commands: https://github.com/turt2live/matrix-dimension/blob/6964bca40e3b1a58a11b8b3be89841e9a94c65cf/src/version.ts#L13-L20

However, its Docker container image (Dockerfile) does not install git. Adding RUN apk add --no-cache git to the Dockerfile should solve this error."

Dimension ran fine before, so I assume it has to do with the docker-image pushed last month.

**Comment by TheTimeWalker** [comment] 2021-11-25 14:55
Does Dimension stop working altogether if this happens or is it just printing that error?

**Comment by janonym1** [comment] 2021-11-25 14:58
the service never starts up: 
`matrix-dimension.service: Main process exited, code=exited, status=1/FAILURE`

**Comment by TheTimeWalker** [comment] 2021-11-25 15:00
That's strange. The error you see looks to be more like a duplicate of https://github.com/turt2live/matrix-dimension/issues/357. It shouldn't stop since it gets caught and only a console error gets printed and should thus continue. This looks more like an unrelated issue. Are you sure there is nothing more in the log?

**Comment by janonym1** [comment] 2021-11-25 15:07
Maybe I misunderstood something, but to be safe, I am posting the whole related log in detail:
```
Nov 25 16:04:31 matrix-dimension[1380610]: Starting matrix-dimension
Nov 25 16:04:31 matrix-dimension[1380610]: version Error: Cannot find module '../package.json'
Nov 25 16:04:31 matrix-dimension[1380610]: Require stack:
Nov 25 16:04:31 matrix-dimension[1380610]: - /home/node/matrix-dimension/build/app/version.js
Nov 25 16:04:31 matrix-dimension[1380610]: - /home/node/matrix-dimension/build/app/index.js
Nov 25 16:04:31 matrix-dimension[1380610]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
Nov 25 16:04:31 matrix-dimension[1380610]:     at Function.Module._load (internal/modules/cjs/loader.js:745:27)
Nov 25 16:04:31 matrix-dimension[1380610]:     at Module.require (internal/modules/cjs/loader.js:961:19)
Nov 25 16:04:31 matrix-dimension[1380610]:     at require (internal/modules/cjs/helpers.js:92:18)
Nov 25 16:04:31 matrix-dimension[1380610]:     at Object.<anonymous> (/home/node/matrix-dimension/build/app/version.js:8:21)
Nov 25 16:04:31 matrix-dimension[1380610]:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
Nov 25 16:04:31 matrix-dimension[1380610]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
Nov 25 16:04:31 matrix-dimension[1380610]:     at Module.load (internal/modules/cjs/loader.js:937:32)
Nov 25 16:04:31 matrix-dimension[1380610]:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
Nov 25 16:04:31 matrix-dimension[1380610]:     at Module.require (internal/modules/cjs/loader.js:961:19)
Nov 25 16:04:31 matrix-dimension[1380610]:     at require (internal/modules/cjs/helpers.js:92:18)
Nov 25 16:04:31 matrix-dimension[1380610]:     at Object.<anonymous> (/home/node/matrix-dimension/build/app/index.js:8:19)
Nov 25 16:04:31 matrix-dimension[1380610]:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
Nov 25 16:04:31 matrix-dimension[1380610]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
Nov 25 16:04:31 matrix-dimension[1380610]:     at Module.load (internal/modules/cjs/loader.js:937:32)
Nov 25 16:04:31 matrix-dimension[1380610]:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
Nov 25 16:04:31 matrix-dimension[1380610]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
Nov 25 16:04:31 matrix-dimension[1380610]:     at internal/main/run_main_module.js:17:47 {
Nov 25 16:04:31 matrix-dimension[1380610]:   code: 'MODULE_NOT_FOUND',
Nov 25 16:04:31 matrix-dimension[1380610]:   requireStack: [
Nov 25 16:04:31 matrix-dimension[1380610]:     '/home/node/matrix-dimension/build/app/version.js',
Nov 25 16:04:31 matrix-dimension[1380610]:     '/home/node/matrix-dimension/build/app/index.js'
Nov 25 16:04:31 matrix-dimension[1380610]:   ]
Nov 25 16:04:31 matrix-dimension[1380610]: }
Nov 25 16:04:31 matrix-dimension[1380610]: /bin/sh: git: not found
Nov 25 16:04:31 matrix-dimension[1380610]: version Error: Command failed: git rev-parse --short HEAD
Nov 25 16:04:31 matrix-dimension[1380610]: /bin/sh: git: not found
Nov 25 16:04:31 matrix-dimension[1380610]:     at checkExecSyncError (child_process.js:760:11)
Nov 25 16:04:31 matrix-dimension[1380610]:     at Object.execSync (child_process.js:833:15)
Nov 25 16:04:31 matrix-dimension[1380610]:     at Object.<anonymous> (/home/node/matrix-dimension/build/app/version.js:16:10)
Nov 25 16:04:31 matrix-dimension[1380610]:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
Nov 25 16:04:31 matrix-dimension[1380610]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
Nov 25 16:04:31 matrix-dimension[1380610]:     at Module.load (internal/modules/cjs/loader.js:937:32)
Nov 25 16:04:31 matrix-dimension[1380610]:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
Nov 25 16:04:31 matrix-dimension[1380610]:     at Module.require (internal/modules/cjs/loader.js:961:19)
Nov 25 16:04:31 matrix-dimension[1380610]:     at require (internal/modules/cjs/helpers.js:92:18)
Nov 25 16:04:31 matrix-dimension[1380610]:     at Object.<anonymous> (/home/node/matrix-dimension/build/app/index.js:8:19)
Nov 25 16:04:31 matrix-dimension[1380610]:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
Nov 25 16:04:31 matrix-dimension[1380610]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
Nov 25 16:04:31 matrix-dimension[1380610]:     at Module.load (internal/modules/cjs/loader.js:937:32)
Nov 25 16:04:31 matrix-dimension[1380610]:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
Nov 25 16:04:31 matrix-dimension[1380610]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
Nov 25 16:04:31 matrix-dimension[1380610]:     at internal/main/run_main_module.js:17:47 {
Nov 25 16:04:31 matrix-dimension[1380610]:   status: 127,
Nov 25 16:04:31 matrix-dimension[1380610]:   signal: null,
Nov 25 16:04:31 matrix-dimension[1380610]:   output: [
Nov 25 16:04:31 matrix-dimension[1380610]:     null,
Nov 25 16:04:31 matrix-dimension[1380610]:     <Buffer >,
Nov 25 16:04:31 matrix-dimension[1380610]:   status: 127,
Nov 25 16:04:31 matrix-dimension[1380610]:   signal: null,
Nov 25 16:04:31 matrix-dimension[1380610]:   output: [
Nov 25 16:04:31 matrix-dimension[1380610]:     null,
Nov 25 16:04:31 matrix-dimension[1380610]:     <Buffer >,
Nov 25 16:04:31 matrix-dimension[1380610]:     <Buffer 2f 62 69 6e 2f 73 68 3a 20 67 69 74 3a 20 6e 6f 74 20 66 6f 75 6e 64 0a>
Nov 25 16:04:31 matrix-dimension[1380610]:   ],
Nov 25 16:04:31 matrix-dimension[1380610]:   pid: 15,
Nov 25 16:04:31 matrix-dimension[1380610]:   stdout: <Buffer >,
Nov 25 16:04:31 matrix-dimension[1380610]:   stderr: <Buffer 2f 62 69 6e 2f 73 68 3a 20 67 69 74 3a 20 6e 6f 74 20 66 6f 75 6e 64 0a>
Nov 25 16:04:31 matrix-dimension[1380610]: }
Nov 25 16:04:31 matrix-dimension[1380610]: Nov-25-2021 15:04:31.938 +00:00 info [index] Starting dimension Unknown
Nov 25 16:04:31 matrix-dimension[1380610]: Nov-25-2021 15:04:31.939 +00:00 info [DimensionStore] Updating schema...
Nov 25 16:04:31 matrix-dimension[1380610]: (node:1) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
Nov 25 16:04:31 matrix-dimension[1380610]: (Use `node --trace-warnings ...` to show where the warning was created)
Nov 25 16:04:36 matrix-dimension[1380610]: ConnectionError [SequelizeConnectionError]: getaddrinfo EAI_AGAIN matrix_dimension_user
Nov 25 16:04:36 matrix-dimension[1380610]:     at Client._connectionCallback (/home/node/matrix-dimension/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:184:24)
Nov 25 16:04:36 matrix-dimension[1380610]:     at Client._handleErrorWhileConnecting (/home/node/matrix-dimension/node_modules/pg/lib/client.js:305:19)
Nov 25 16:04:36 matrix-dimension[1380610]:     at Client._handleErrorEvent (/home/node/matrix-dimension/node_modules/pg/lib/client.js:315:19)
Nov 25 16:04:36 matrix-dimension[1380610]:     at Connection.emit (events.js:400:28)
Nov 25 16:04:36 matrix-dimension[1380610]:     at Socket.reportStreamError (/home/node/matrix-dimension/node_modules/pg/lib/connection.js:52:12)
Nov 25 16:04:36 matrix-dimension[1380610]:     at Socket.emit (events.js:400:28)
Nov 25 16:04:36 matrix-dimension[1380610]:     at emitErrorNT (internal/streams/destroy.js:106:8)
Nov 25 16:04:36 matrix-dimension[1380610]:     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
Nov 25 16:04:36 matrix-dimension[1380610]:     at processTicksAndRejections (internal/process/task_queues.js:82:21) {
Nov 25 16:04:36 matrix-dimension[1380610]:   parent: Error: getaddrinfo EAI_AGAIN matrix_dimension_user
Nov 25 16:04:36 matrix-dimension[1380610]:       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26) {
Nov 25 16:04:36 matrix-dimension[1380610]:     errno: -3001,
Nov 25 16:04:36 matrix-dimension[1380610]:     code: 'EAI_AGAIN',
Nov 25 16:04:36 matrix-dimension[1380610]:     syscall: 'getaddrinfo',
Nov 25 16:04:36 matrix-dimension[1380610]:     hostname: 'matrix_dimension_user'
Nov 25 16:04:36 matrix-dimension[1380610]:   },
Nov 25 16:04:36 matrix-dimension[1380610]:   original: Error: getaddrinfo EAI_AGAIN matrix_dimension_user
Nov 25 16:04:36 matrix-dimension[1380610]:       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26) {
Nov 25 16:04:36 matrix-dimension[1380610]:     errno: -3001,
Nov 25 16:04:36 matrix-dimension[1380610]:     code: 'EAI_AGAIN',
Nov 25 16:04:36 matrix-dimension[1380610]:     syscall: 'getaddrinfo',
Nov 25 16:04:36 matrix-dimension[1380610]:     hostname: 'matrix_dimension_user'
Nov 25 16:04:36 matrix-dimension[1380610]:   }
Nov 25 16:04:36 matrix-dimension[1380610]: }
Nov 25 16:04:37 systemd[1]: matrix-dimension.service: Main process exited, code=exited, status=1/FAILURE

```

**Comment by TheTimeWalker** [comment] 2021-11-25 15:32
Yes, seems like the database error is the culprit and not the git error. Is your hostname (or docker container name) matrix_dimension_user?

**Comment by janonym1** [comment] 2021-11-25 15:39
Yeah, I think so too. If I can safely ignore the messages at the dimension-service startup regarding git, then it can only be my postgreSQL connection. 

I am looking into as to why it uses the wrong `hostname: 'matrix_dimension_user'` instead of the real hostname of my DB since the playbook variable clearly states: `matrix_dimension_database_hostname: 'hostname'` and `matrix_dimension_database_username: 'matrix_dimension_user'` but this is probably an playbook issue and unrelated to the image. 

Thanks anyways for your help! I will close this soon

**Closed** 2021-11-25 15:42 UTC
