### ISSUE TITLE
Adding bridge breaks up integration manager

### ISSUE THREAD

**Issue by flozi00** [turt2live/matrix-dimension#375] opened 2020-09-20 09:31 UTC
PLEASE NOTE: make sure the bug exists in the latest patch level of the project. For instance, if you are running a 2.x version of Apostrophe, you should use the latest in that major version to confirm the bug.

## To Reproduce

Step by step instructions to reproduce the behavior:

Open the integration manager
Go to settings
go to bridges
go to slack bridge
click in add matrix.org bridge

now there is no way to configure or remove the bridge, I am not able to add this bridge to a room too.

I am using Ubuntu 18, the newest ansible version and docker version of matrix-dimension

**Comment by turt2live** [comment] 2020-09-20 16:20
Duplicate of https://github.com/turt2live/matrix-dimension/issues/199

**Closed by turt2live** 2020-09-20 16:20 UTC
Labels: bug
