### ISSUE TITLE
Remove third party cdn's

### ISSUE THREAD

**Issue by Perflyst** [turt2live/matrix-dimension#270] opened 2019-04-06 11:42 UTC
At the moment `https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css` is loaded from maxcdn as third party. Also some other CSS files are loaded from third party.
I would prefer to have it locally instead. Is there any need for this third party? I dont think so.

**Comment by turt2live** [comment] 2019-04-06 16:31
Duplicate of https://github.com/turt2live/matrix-dimension/issues/256

**Closed by turt2live** 2019-04-06 16:31 UTC
