### ISSUE TITLE
Stickers are not working anymore

### ISSUE THREAD

**Issue by smoebody** [turt2live/matrix-dimension#337] opened 2020-04-07 17:27 UTC
Dimension: v1.0.0-eb3c450
Riot-Web: 1.5.15
Synapse: 1.12.3

I don't know since when its the case - usually i use the android-app - but since recently the sticker-picker in the riot-webapp is not working anymore.

I can open the integration managment, choose what sticker packs i want, but  when i want to choose a sticker i only get the unfolding-animation endlessly.

![image](https://user-images.githubusercontent.com/991327/78699010-7996a500-7903-11ea-892b-2a5cbdcf43ed.png)

This is the dimension-log (obfuscated):
```
Apr-7-2020 17:14:22.987 +00:00 info [Webserver] Incoming request: GET /widgets/stickerpicker?widgetId=dimension-stickerpicker-1578924959137&parentUrl=https%3A%2F%2Fchat.example.com%2F
Apr-7-2020 17:14:23.400 +00:00 info [BotSdk-MatrixLiteClient (REQ-97 RESP-H200)] {"account_data":{"events":{}},"to_device":{"events":{}},"device_lists":{"changed":{},"left":{}},"presence":{"events":{}},"rooms":{"join":{},"invite":{},"leave":{}},"groups":{"join":{},"invite":{},"leave":{}},"device_one_time_keys_count":{"signed_curve25519":50},"next_batch":"s312346_21010869_4122_404588_17753_67_334_84742_2"}
Apr-7-2020 17:14:23.401 +00:00 info [BotSdk-MatrixClientLite] Received sync. Next token: s312346_21010869_4122_404588_17753_67_334_84742_2
Apr-7-2020 17:14:23.403 +00:00 info [BotSdk-MatrixClientLite] Performing sync with token s312346_21010869_4122_404588_17753_67_334_84742_2
Apr-7-2020 17:14:23.404 +00:00 info [BotSdk-MatrixLiteClient (REQ-98)] GET https://matrix.example.com/_matrix/client/r0/sync
Apr-7-2020 17:14:23.404 +00:00 info [BotSdk-MatrixLiteClient (REQ-98)] qs = {"full_state":false,"timeout":10000,"since":"s312346_21010869_4122_404588_17753_67_334_84742_2"}
Apr-7-2020 17:14:33.444 +00:00 info [BotSdk-MatrixLiteClient (REQ-98 RESP-H200)] {"account_data":{"events":{}},"to_device":{"events":{}},"device_lists":{"changed":{},"left":{}},"presence":{"events":{}},"rooms":{"join":{},"invite":{},"leave":{}},"groups":{"join":{},"invite":{},"leave":{}},"device_one_time_keys_count":{"signed_curve25519":50},"next_batch":"s312346_21010882_4122_404588_17753_67_334_84742_2"}
```

This is the riot-webapp console log
```
Widget dimension-stickerpicker-1578924959137 requested capabilities: m.sticker
bundle.js:2 Widget dimension-stickerpicker-1578924959137 allowing requested, whitelisted properties: m.sticker
e.<computed> @ bundle.js:2
(anonymous) @ bundle.js:2
Promise.then (async)
_setupWidgetMessaging @ bundle.js:2
_onLoaded @ bundle.js:2
s @ bundle.js:2
h @ bundle.js:2
(anonymous) @ bundle.js:2
_ @ bundle.js:2
at @ bundle.js:2
rt @ bundle.js:2
st @ bundle.js:2
ht @ bundle.js:2
re @ bundle.js:2
ce @ bundle.js:2
Xt @ bundle.js:2
Jt @ bundle.js:2
load (async)
Yt @ bundle.js:2
Wt @ bundle.js:2
Qa @ bundle.js:2
uc @ bundle.js:2
lc @ bundle.js:2
sc @ bundle.js:2
Zs @ bundle.js:2
(anonymous) @ bundle.js:2
t.unstable_runWithPriority @ bundle.js:2
Vr @ bundle.js:2
Wr @ bundle.js:2
Kr @ bundle.js:2
ne @ bundle.js:2
$t @ bundle.js:2
scalar-widget.api.ts:138 [Dimension] Received fromWidget response at widget ID dimension-stickerpicker-1578924959137: {"api":"fromWidget","widgetId":"dimension-stickerpicker-1578924959137","action":"supported_api_versions","requestId":"F9D3Hacw0wRSHYUUq0NfJL7SR4O6jbXiYAEPhkG5H7I6VSrMFmfOUzsJIARCfgq3BmmI6jd4EuTJNNvuEn8rUaFN9xMOskOTqckcboJubvxEJubKebYvIGFcYxFVPKK2N7LWv1zgALfrwu4oO1NgszjjinnJgKaD","response":{"api":"fromWidget","supported_versions":["0.0.1","0.0.2"]}}
scalar-widget.api.ts:108 [Dimension] Sending fromWidget:  {api: "fromWidget", widgetId: "dimension-stickerpicker-1578924959137", action: "get_openid", requestId: "PWl673lu1dZ8I6Ce4ClxwFzOxT6BEylsA1030ZEmfSmcByDI6M…QDf5xX2SYe7nDskbh7rHv4I3VctXWFtIrAKkjIp3I49W11b5S"}
bundle.js:2 Uncaught (in promise) Error: No matching user widget to form security key
    at Function.getWidgetSecurityKey (bundle.js:2)
    at d._onOpenIdRequest (bundle.js:2)
    at m.onPostMessage (bundle.js:2)
```

**Comment by turt2live** [comment] 2020-04-21 22:32
I can't reproduce this, and it sounds like https://github.com/vector-im/riot-web/issues/13131 anyways. Closing in favour of the riot-web bug as it sounds like a client issue (the error comes from Riot, not Dimension).

**Closed by turt2live** 2020-04-21 22:32 UTC

**Comment by oleg-fiksel** [comment] 2020-05-14 17:21
Stickers work with Riot 1.6.1-rc.1 🎉  !
* https://github.com/vector-im/riot-web/releases/tag/v1.6.1-rc.1
