### ISSUE TITLE
User whitelist

### ISSUE THREAD

**Issue by Bubu** [turt2live/matrix-dimension#360] opened 2020-07-04 18:50 UTC
As far as I can see there's no whitelist of allowed users for a dimension installation. I'd like to restrict usage to users of my homserver. Would such a thing be possible?

**Comment by turt2live** [comment] 2020-07-04 19:16
Duplicate of https://github.com/turt2live/matrix-dimension/issues/110

**Closed by turt2live** 2020-07-04 19:16 UTC
