### ISSUE TITLE
disabled widgets disappear from admin panel completely

### ISSUE THREAD

**Issue by HarHarLinks** [turt2live/matrix-dimension#463] opened 2022-01-10 17:14 UTC
![image](https://user-images.githubusercontent.com/2803622/148808744-65a1206e-f680-467c-ba30-abb8ed450a52.png)

1. disable some in the admin panel
2. log out and back in
3. look at admin panel
4. the disabled widgets have disappeared completely

**Comment by TheTimeWalker** [comment] 2022-01-10 17:23
Duplicate of https://github.com/turt2live/matrix-dimension/issues/306

**Closed** 2022-01-10 17:36 UTC
