### ISSUE TITLE
 Grafana Widget does not work in Windows App but in Browser

### ISSUE THREAD

**Issue by vmario89** [turt2live/matrix-dimension#254] opened 2019-03-21 12:12 UTC
Hi,
i have the following behaviour using different Riot client platfforms:

 -   displaying Grafana widget inside riot.fablabchemnitz.de works fine (version 1.0.4-rc1)
 -   displaying Grafana wdiget outside riot client, which is redirected to https://dimension.fablabchemnitz.de/widgets/generic-fullscreen?url=https.... and so and works fine too
-    displaying Grafana widget inside Windows Riot Client (v1.0.4) does not work. It gives prompt to login inside Grafana. After entering credentials nothing happens. just showing login mask again

I am running exact same config.json for Windows App and web client.

I made this issue first at Riot side but seems to be related directly to Dimension instead. Could you maybe have a look into it? thanks and regards, Mario

ps: this was conversation to this problem https://github.com/vector-im/riot-web/issues/9167

**Comment by turt2live** [comment] 2019-03-24 00:56
I'm not able to reproduce this, and based on the information in https://github.com/vector-im/riot-web/issues/9167 it doesn't work with Scalar (the default manager) either. Closing this to handle it over there.

**Closed by turt2live** 2019-03-24 00:56 UTC
